import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    fontSize: 25,
    marginBottom: 50,
    backgroundColor: "#23e3f3",
    marginTop: 20,
  },
  login: {
    fontSize: 25,
    marginBottom: 20,
    color: "#23e3f3",
  },
  input: {
    width: 300,
    height: 40,
    borderColor: "black",
    borderWidth: 1,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  inputField: {
    fontSize: 20,
    margin: 5,
    padding: 2,
  },
  buttonact: {
    backgroundColor: "#23e3f3",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    width: 100,
    margin: 15,
  },
  buttonact2: {
    backgroundColor: "#88c425",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    width: 100,
    margin: 15,
  },
  title: {
    fontSize: 25,
    margin: 5,
  },
  cad: {
    fontSize: 20,
    textAlign: "center",
  },
  buttonSair: {
    backgroundColor: "#e94648",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    width: 100,
    marginBottom: 20,
  },
  menu: {
    borderWidth: 1,
    padding: 10,
    margin: 10,
    borderRadius: 5,
  },
  textoMenu: {
    fontSize: 23,
  },
  grupoMenu: {
    margin: 15,
  },
  btnCancel: {
    backgroundColor: "#e94648",
    paddingRight: 2,
    borderRadius: 5,
    width: 70,
    marginBottom: 20,
    alignItems: 'center',
    marginTop: 10,
  },
  select: {
    borderWidth: 1,
    padding: 10,
    margin: 5,
  },
  calend: {
    alignItems: "center",
    width: 150,
  },
  data: {
    fontSize: 15,
    color: "red",
    marginBottom: 15,
  },
  bemVindo: {
    fontSize: 20,
    fontWeight: "bold",
  },
  fundo: {
    borderWidth: 2,
    margin: 10,
    padding: 20,
    borderRadius: 10,
  },
  titleLogin: {
    fontSize: 20,
  },
  fundo1: {
    alignItems: "center",
    backgroundColor: "#23e3f3",
    borderTopStartRadius: 5,
    borderTopEndRadius: 5,
    marginRight: -20,
    marginLeft: -20,
    marginTop: -20,
    padding: 10,
    borderBottomWidth: 1,
  },
  inside: {
    alignItems: "center",
    paddingTop: 10,
  },
  fundo3: {
    borderWidth: 2,
    margin: 10,
    padding: 20,
    borderRadius: 10,
  },
  fundo4: {
    alignItems: "center",
    backgroundColor: "#23e3f3",
    borderTopStartRadius: 5,
    borderTopEndRadius: 5,
    marginRight: -20,
    marginLeft: -20,
    marginTop: -20,
    padding: 10,
    borderBottomWidth: 1,
  },
  fundoCad: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderRadius: 10,
    margin: 10,
  },
  fundoCad1: {
    borderTopStartRadius: 9,
    borderTopEndRadius: 9,
    backgroundColor: "#23e3f3",
    padding: 12,
    borderBottomWidth: 1,
    marginTop: 53,
    width: 350,
  },
  fundoCad3: {
    padding: 20,
  },
  voltar: {
    marginTop: 15,
  },
  cadCentro: {
    flex: 1,
    alignItems: "center",
    marginTop: 15,
    marginBottom: -15,
  },
  dashCad1: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderRadius: 10,
    margin: 20,
  },
  dashCad2: {
    borderTopStartRadius: 9,
    borderTopEndRadius: 9,
    backgroundColor: "#23e3f3",
    width: 340,
    padding: 10,
    alignItems: "center",
    borderBottomWidth: 1,
  },
  titleDash: {
    fontSize: 20,
  },
  schedCad: {
    borderWidth: 2,
    borderRadius: 10,
    padding: 15,
  },
  schedCad1: {
    borderTopStartRadius: 9,
    borderTopEndRadius: 9,
    backgroundColor: "#23e3f3",
    padding: 12,
    borderBottomWidth: 1,
    margin: -15,
    marginBottom: 5,
    alignItems: "center",
  },
  schedCad2: {
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  picker: {
    borderWidth: 1,
  },
  lSched: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderRadius: 10,
    width: 300,
    position: "fixed",
    height: 500,
  },
  lSched1:{
    borderTopStartRadius: 9,
    borderTopEndRadius: 9,
    backgroundColor: "#23e3f3",
    padding: 12,
    borderBottomWidth: 1,
    alignItems: "center",
    width: 297,
    marginBottom: 5,
  },
  lSched2: {
    justifyContent: "center",
    alignItems: "center",
    width: 280,
  },
  view: {
    width: 200,
    gap: 10,
    borderWidth: 1,
    margin: 10,
    backgroundColor: '#faf6d0',
    padding: 5,
  },
  buttonCancelAjust: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  titleAgend: {
    fontSize: 20,
  }
});
